### ISSUE TITLE
Basic request to PFS server

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#82]
## Description

**As Josh I want to be able to**

know that the PFS I selected works

**So that I can**

be sure that I will get routes later if required.

## Acceptance Criteria

- [x] PFS answers on general info route
- [x] PFS returns settings/infos (versionsnummer, IP, betreiber)
- [x] PFS can be run locally and remotely
- [ ] PFS can be updated easily 

## Related story / issue
- #80

## Tasks
- [x] Implement endpoint
- [x] Test endpoint
- [x] Setup meeting with Ulo
- [ ] Define requirements for deployment
- [ ] Setup deployment pipeline

**Comment by Dominik1999** [comment]
PFS returns info IP address might not be really useful. The external IP, as @karlb pointed out, is probably known to a user who reaches the server. Maybe we can show the ETH address instead? Every PFS would need to have an ETH address with which it is registered at a certain smart contract, right?

**Comment by karlb** [comment]
> PFS returns info IP address might not be really useful. The external IP, as @karlb pointed out, is probably known to a user who reaches the server. Maybe we can show the ETH address instead? Every PFS would need to have an ETH address with which it is registered at a certain smart contract, right?

If you have that at hand then add it. Otherwise just show the version number for now. We can easily add new fields later.

**Comment by palango** [comment]
Progress of the remaining tasks will be tracked on #127
