### ISSUE TITLE
PFS provides the shortest path

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#83]
## Description

**As Josh I want to be able to**

ask the PFS for a path between two nodes

**So that I can**

see the route between two nodes.

## Acceptance Criteria

- [x] API endpoint for path requests via HTTP
- [x] Path is returned as JSON Object
- [x] Interface is accepted by the client team
- [x] List with addresses which represent the route (A -> B -> C)
- [x] Shortest route provided
- [x] Tested via HTTP endpoint
- [x] Unit tests for routing

## Story Points

13

## Tasks
- [x] Define interface
- [x] Clarify interface with Lefteris
- [x] Start Http interface with PathfindingService
- [x] Set default fee to 0
- [x] Check coverage of existing tests, fix if necessary

## Related story / issue
-

**Comment by karlb** [comment]
I like the interface for the `paths` endpoint given at https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#api-1-token-network-address-paths

@LefterisJP: can we go ahead with that, or will something else be more useful for the raiden client?

**Comment by karlb** [comment]
> What is the `num_paths` exactly? How many paths we want? Or the maximum number of paths that we are interested in?

Since we can only a limited number of valid routes, `num_paths` has to be the maximum number of routes the client is interested in. `max_paths` is clearer in that regard.

> I suppose other errors would also be that:
> 
>     * the `token network address` is invalid.
>     * `bias` is not a valid number
>     * `num_paths` is not a valid number
>     * `value` is not a valid number

Yes, I'll add those.

> It would be nice if you had `"errors"` as the keyword argument instead to be in sync with how we return errors in the Raiden API.

Having a plural key `errors` with a single value inside is counter-intuitive for me. But I guess consistency is more important.
