### ISSUE TITLE
PFS provides multiple paths

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#84]
## Description

**As Josh I want to be able to**

get multiple options for routing a payment

**So that I can**

try another route when one fails.

## Acceptance Criteria

- [x] PFS endpoints provides multiple routes for a given payment
- [x] List of routes as JSON
- [x] Same endpoint as #83 
- [x] Routes sorted by the number of hops increasing

## Story Points

5

## Related story / issue
- #83 

## Tasks
- [x] Define interface
- [x] Check interface with Lefteris
- [x] Check coverage, add tests if necessary
- [x] Test proper sorting of routes
