### ISSUE TITLE
Number of routes returned by PFS can be configured

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden-pathfinding-service#86]
## Description

**As Josh I want to be able to**

set the routes that should be returned by the PFS

**So that I can**

get an optimized answer in case I want this.

## Acceptance Criteria

- [x] There is an argument one can pass with the request to the PFS that sets, how many routes the PFS provides
- [x] The argument has a default
- [x] The PFS server would react according to the configured argument and send the requested number routes (or a number in case the routes are not sent yet)

## Story points
2

## Tasks
- [x] Check implementation
- [x] Define default number of routes

**Comment by karlb** [comment]
@palango, @Dominik1999: How do we want to choose the default number? Do we just decide among ourselves, or do we want/need to involve someone else?

**Comment by palango** [comment]
Let's bring @LefterisJP in the discussion.

I'd put the default bigger than 3, especially in the beginning when we don't have balance data.

**Comment by LefterisJP** [comment]
I assume this is for the max paths returned by PFS? As @palango says since there is no balance data in the beginning I would go for max information, so perhaps a big number? Why have a small number? Are we trying to optimize for something?

**Comment by karlb** [comment]
> I assume this is for the max paths returned by PFS? As @palango says since there is no balance data in the beginning I would go for max information, so perhaps a big number? Why have a small number? Are we trying to optimize for something?

You probably won't actually try to use a very large number of routes (takes a long time, things might change in the mean time). A smaller number of routes is also nicer to look at in documentation and debugging (which are cases where the default might be used). But apart from there rather weak arguments, there's not reason to choose a low number. Since it's only a default, we don't have to go very high, either.

To me, everything in the range between 3 and 20 seems like reasonable default. But it's just a default, so I also wouldn't have problems with any other value.

**Comment by palango** [comment]
I'm fine with 5 for now, we can still adapt this as soon as we see problems while integrating the PFS into Raiden.

**Comment by LefterisJP** [comment]
5 sounds good. We can always change it if live testing shows us it's not a good number.
